apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jx3-terraform-eks
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "763365863673"
    provider: eks
    region: eu-central-1
    registry: 763365863673.dkr.ecr.eu-central-1.amazonaws.com
  environments:
  - key: dev
    owner: ftl-faxiang
    repository: jx3-eks-asm
  - key: staging
  - key: production
  ingress:
    domain: skygo.fr
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: StevensGitHub
  repository: nexus
  secretStorage: secretsManager
  storage:
  - name: logs
    url: s3://logs-jx3-terraform-eks-20211117015134686900000004
  - name: reports
    url: s3://reports-jx3-terraform-eks-20211117015134700200000007
  - name: repository
    url: s3://repository-jx3-terraform-eks-20211117015134702600000008
  terraform: true
  vault:
    aws:
      dynamoDBRegion: eu-central-1
      dynamoDBTable: vault-unseal-jx3-terraform-eks-7FYlXCDY
      iamUserName: chenzuoming
      kmsKeyId: 97429887-1457-4d43-b48b-4b27341af2d4
      kmsRegion: eu-central-1
      s3Bucket: vault-unseal-jx3-terraform-eks-20211117015134681700000003
      s3Region: eu-central-1
  webhook: lighthouse
