apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        ftl-faxiang/golang-test2: true
        ftl-faxiang/jx3-eks-asm: true
        ftl-faxiang/test1: true
        ftl-faxiang/test2: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        ftl-faxiang/golang-test2: merge
        ftl-faxiang/jx3-eks-asm: merge
        ftl-faxiang/test1: merge
        ftl-faxiang/test2: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - ftl-faxiang/jx3-eks-asm
        - ftl-faxiang/golang-test2
        - ftl-faxiang/test1
        - ftl-faxiang/test2
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - ftl-faxiang/jx3-eks-asm
        - ftl-faxiang/golang-test2
        - ftl-faxiang/test1
        - ftl-faxiang/test2
      target_url: http://lighthouse-jx.skygo.fr/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
