apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: ftl-faxiang
    provider: https://github.com
    providerKind: github
    repositories:
    - name: golang-test2
    - name: test1
    - name: test10
    - name: test2
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
